run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gofmt

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
