version: 2

builds:
  - main: ./cmd/gottp
    binary: gottp
    ldflags:
      - -s -w
      - -X github.com/serdar/gottp/pkg/version.Version={{.Version}}
      - -X github.com/serdar/gottp/pkg/version.Commit={{.ShortCommit}}
      - -X github.com/serdar/gottp/pkg/version.Date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  use: github-native

brews:
  - repository:
      owner: sadopc
      name: homebrew-tap
    directory: Formula
    homepage: "https://github.com/sadopc/gottp"
    description: "A Postman/Insomnia-like TUI API client built in Go"
    license: "MIT"
    install: |
      bin.install "gottp"
    test: |
      assert_match version.to_s, shell_output("#{bin}/gottp --version")

release:
  github:
    owner: sadopc
    name: gottp
