version: 2

builds:
  - main: ./cmd/gottp
    binary: gottp
    ldflags:
      - -s -w
      - -X github.com/serdar/gottp/pkg/version.Version={{.Version}}
      - -X github.com/serdar/gottp/pkg/version.Commit={{.ShortCommit}}
      - -X github.com/serdar/gottp/pkg/version.Date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  use: github-native

release:
  github:
    owner: serdar
    name: gottp
